### ISSUE TITLE
[BUG] Live Inspect interface show blank after choosing Entire app and select an app in Accessibility Insights for Windows

### ISSUE THREAD

**Issue by Michellehdr** [microsoft/accessibility-insights-windows#1845] opened 2024-07-10 21:23 UTC
**Describe the bug**
Live Inspect interface show blank after choosing Entire app and select an app in Accessibility Insights for Windows

**To Reproduce**

1. Install the Accessibility insights tool for Windows from https://accessibilityinsights.io
2. In Accessibility Insights for Windows, go to the Live Inspect view
3. Under What to select, choose Entire app
4. Select an app
5. Find Live Inspect interface show blank after choosing Entire app and select an app in Accessibility Insights for Windows===>Problem

**Expected behavior**
Live Inspect interface show information after choosing Entire app and select an app in Accessibility Insights for Windows

**Actual behavior**
Live Inspect interface show blank after choosing Entire app and select an app in Accessibility Insights for Windows

**Screenshots or .GIF**

**Desktop (please complete the following information):**
 - OS: [Windows 11 26090.1] 
 - Accessibility Insights for Windows Version: 1.1.2703.1

**Comment by JeevaniChinthala** [comment] 2024-07-12 05:35
Hi Michell, Thanks for reaching out to us. We were unable to reproduce the issue with the version you provided. Could you please provide more details? Specifically, let us know which application you used for testing and attach screenshots as well.

**Comment by Michellehdr** [comment] 2024-07-15 18:34
@JeevaniChinthala the issue we observed is on Accessibility Insights for Windows. The information I shared above is all I have. Please kindly let me know what other information needed.

**Comment by v-viyada** [comment] 2024-07-15 18:40
@Michellehdr, Could you please screen record the steps you are trying and share with us. This will help us in investigating the issue. Thanks.

**Comment by Michellehdr** [comment] 2024-07-16 21:57
@v-viyada This bug is from a user feedback and I don't have a screen record of it. But I did attach a screenshot in my original reporting. Could you please take a look?

**Comment by v-sharmachir** [comment] 2024-07-17 05:28
@Michellehdr we can't see any screenshot attached. Could you please reattach that?

**Comment by Michellehdr** [comment] 2024-07-17 16:58
![Screenshot](https://github.com/user-attachments/assets/901df5f9-56c6-43f1-8e6c-58f78195faa3)
@v-sharmachir attach again. Please check

**Comment by v-sharmachir** [comment] 2024-07-18 13:53
@Michellehdr the screenshot you provided seems to be old, and it's not clear which app was used for the test. Could you please reach out to the end user who did the initial test and ask them to try it again with the latest version? Please have them include the app details this time. Also, a screen recording would really help us pinpoint the problem.

**Comment by Michellehdr** [comment] 2024-08-23 22:00
@v-sharmachir we verified the bug on latest App and OS, the bug still repro. App version: 1.1.2703.1. It repro on Windows GE build, not repro on NI and SV2.

**Comment by Michellehdr** [comment] 2024-09-04 21:49
@v-sharmachir is there any update for this bug?

**Comment by codeofdusk** [comment] 2024-09-05 02:28
Duplicate of #1837.

**Closed by codeofdusk** 2024-09-05 02:28 UTC
Labels: bug, status: new
