### ISSUE TITLE
[BUG] AADSTS90015: Requested query string is too long.

### ISSUE THREAD

**Issue by NCarlsonMSFT** [microsoft/accessibility-insights-windows#1398] opened 2022-08-01 23:16 UTC
Please check whether the bug has [already been filed](https://github.com/Microsoft/accessibility-insights-windows/issues).

This repo contains code for Accessibility Insights for Windows. We maintain code for its automated checks rule engine at [axe-windows](https://github.com/microsoft/axe-windows/issues/). Most false positive questions or rule clarifications belong in [axe-windows](https://github.com/microsoft/axe-windows/issues/new/choose), whereas questions about the Accessibility Insights tool UI should go here. If you aren't sure, it's definitely OK to use this repo. Thanks for contributing!

**Describe the bug**
When trying to use the File issue feature against ADO creating the issue fails with "AADSTS90015: Requested query string is too long."

**To Reproduce**
1. Connect to an Azure Board for filing issues
2. Open an a11ytest file with an issue
3. Click "File Issue:

**Expected behavior**
A new bug is created in the ADO board

**Actual behavior**
Authentication fails

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/14239288/182260326-28796412-43e5-4841-afa2-04994f62c967.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 19044.1826
 - Accessibility Insights for Windows Version: 1.1.1997.01
 - Target Application: Visual Studio
 - Target Application Version: 17.4

**Additional context**
I've tried the mitigations recommended in https://github.com/microsoft/accessibility-insights-windows/issues/1336 to no avail.
Others on my team are being blocked by the same issue.

**Comment by madalynrose** [comment] 2022-08-02 18:02
Thank you for using Accessibility Insights for Windows, @NCarlsonMSFT! We have reproduced this locally and confirmed the bug you identified. We are working on investigating further and will respond here once we determine next steps.

**Comment by madalynrose** [comment] 2022-08-04 20:06
We are working on a more robust fix, but should someone find this issue because they are blocked, I can offer a very hacky temporary workaround:
1. right-click the dialog with the error message and select "Inspect" from the menu
2. select the console inside of DevTools and type `window.location.href = "https://dev.azure.com/YOUR-TEAM-HERE"`
3. close the dialog and retry filing the issue

The dialog seems to work okay once it is able to confirm authentication succeeded but the query parameters used to prepopulate the issue template make the url too long for it to do so.

**Comment by DaveTryon** [comment] 2022-08-29 17:49
This has been fixed in Canary, starting with builds after https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.2046.01. It will be in our next production release

**Closed** 2022-09-21 21:04 UTC
Labels: bug, status: resolved
