### ISSUE TITLE
"Focusable sibling elements must not have the same Name and LocalizedControlType" for about button on ribbon

### ISSUE THREAD

**Issue by skuskusku** [microsoft/accessibility-insights-windows#1848] opened 2024-09-12 14:44 UTC
**How to find reason for "Focusable sibling elements must not have the same Name and LocalizedControlType" for about button on ribbon**

I am in the process of improving our old MFC-based product UI for better accessibility and have made great progress so far, thanks to AI4Win, thank you very much for this product.

One of our apps use the ribbon control from MFCNext, introduced back then with VS2008 SP1. This ribbon control has an about button in the upper right corner that invokes an aboutbox dialog. If I test this button with AI4Win I keep getting the error in the subject line. If I inspect the siblings of this control I can nowhere see an element with the same Name or LocalizedControlType as this about button. Furthermore, if I click the link labeled "View results in the UI Automation tree", I get "No test result" instead of a depiction of the offending element with its siblings in a tree view, as usual. 

I wondered if this is reproducible and just fired up the MFC app wizard in VS2022 in order to have an Office-like application with a ribbon created for me, and lo and behold, this behaviour can be reproduced with any app wizard generated mfc ribbon application.

I have been assigned to fix this bug, but I have no idea what to do here. The following screenshot shows what I get with AI4Win:

![ai4winproblem](https://github.com/user-attachments/assets/894c25fe-2fae-4909-8ebe-0aa4231b7cee)

As you can see, there is no sibling element to the About button with the same Name. If I now click on the test button for this about button in AI4Win, I get the following result:

![ai4winproblem2](https://github.com/user-attachments/assets/d5c6c76b-2e45-4a20-9d2a-600e176d45c3)

Now if I click on "View results in the UI Automation tree", I simply get the not very helpful screen as in the next screenshot:

![ai4winproblem3](https://github.com/user-attachments/assets/fec539ff-90a1-41ed-8e6d-a915964066c2)

What can I do to solve this problem?

Any help appreciated,

-- 
Stefan

**Comment by codeofdusk** [comment] 2024-09-16 17:56
Duplicate of #1838, microsoft/axe-windows#1046.

**Closed by codeofdusk** 2024-09-16 17:56 UTC
Labels: status: new
