### ISSUE TITLE
[BUG] WPF list item scrolled off screen is flagged as `IsOffScreen property must be false`

### ISSUE THREAD

**Issue by donnie-msft** [microsoft/accessibility-insights-windows#1176] opened 2021-08-17 17:45 UTC
Please check whether the bug has [already been filed](https://github.com/Microsoft/axe-windows/issues).

## Describe the bug

An item in a list that is not visible until scrolling down is being flagged as **An element's IsOffScreen property must be false when its clickable point is on screen.**

**To Reproduce**

1. Create a new WPF Application (I tried .NET Framework 4.7.2, 4.8, .NET Core 6.0)
2. Create a simple `ListBox`, bound to a `List<string>`. Use the below XAML and XAML.cs code.
3. Ensure the Window is smaller than the list of items so that Vertical Scrolling is present.
3. Observe that Accessibility Insights reports an item below the window as:
   **An element's IsOffScreen property must be false when its clickable point is on screen.**
```
<Window x:Class="WpfApp5.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d"
        Title="MainWindow" Height="75" Width="100">
    <Grid>
        <ListBox ItemsSource="{Binding Things}"></ListBox>
    </Grid>
</Window>
```

```
using System.Collections.Generic;
using System.Windows;

namespace WpfApp5
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public List<string> Things { get; set; } 

        public MainWindow()
        {
            Things = new List<string>();
            Things.Add("test1");
            Things.Add("test2");
            Things.Add("test3");
            Things.Add("test4");
            Things.Add("test5");
            Things.Add("test6");
            Things.Add("test7");
            Things.Add("test8");
            Things.Add("test9");
            Things.Add("test10");
            Things.Add("test11");
            Things.Add("test12");
            Things.Add("test13");
            Things.Add("test14");
            DataContext = this;
            InitializeComponent();
        }
    }
}

```

## Expected behavior

No error, since the items are within a ScrollView area.

## Actual behavior

First item in the list which is below the viewable area due to scrolling is flagged: 
**An element's IsOffScreen property must be false when its clickable point is on screen.**

## Screenshots or .GIF

![image](https://user-images.githubusercontent.com/49205731/129774457-73cd39e9-b155-4cdc-8b09-b3647bb6690b.png)

## Desktop (please complete the following information):

 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line) Version	10.0.19043 Build 19043
 - Accessibility Insights for Windows Version: 1.1.1663.01
 - Target Application: [e.g. Chrome, Wildlife Manager] WPF
 - Target Application Version: [e.g. 22] N/A

## Additional context

Priority requested -

Possibly related, closed issue? https://github.com/microsoft/axe-windows/issues/357

**Comment by dbjorge** [comment] 2021-08-24 23:36
Hi @donnie-msft ,

This is a duplicate of https://github.com/microsoft/axe-windows/issues/539. Per the discussion in that bug, we believe that Accessibility Insights is correct to report this as a bug and that the root cause is a WPF issue (WPF should not be reporting the element in question as having a clickable point).

It is unlikely that this will ever be fixed in older versions of .NET Framework, but possible that it could be fixed in future .NET versions. https://github.com/dotnet/wpf/issues/5046 appears to be the WPF issue tracking the problem; I've left a reference to this report there and encourage you to upvote that issue!

**Closed** 2021-08-24 23:37 UTC
Labels: bug, status: ready for triage, resolution: out of scope
