### ISSUE TITLE
[BUG] AIWin Events TreeView expandable nodes should have 3-state checkboxes

### ISSUE THREAD

**Issue by guybark** [microsoft/accessibility-insights-windows#815] opened 2020-06-08 19:11 UTC
**Describe the bug**
The Events checkbox UI is unclear as to what events will be reported.

**To Reproduce**
1. Run AIWin and get to its Events treeview in preparation to listening for FocusChanged and LiveRegionChanged events.
2. Check and uncheck individual events' radio buttons until only the checkboxes for the FocusChanged and LiveRegionChanged events are checked.

**Expected behavior**
The Events UI should be unambiguous as to what events are going to be reported. As such, if a parent treeview node has some child nodes with a checked checkbox, and some child nodes with an unchecked checkbox, the parent node's checkbox should have an Indeterminate state.

**Actual behavior**
Depending on the steps taken for checking the events' checkboxes of interest, the checkboxes for the parent treeview nodes may or may not be checked. If that checkbox is unchecked, some customer may feel that all its child nodes are effectively unchecked, despite some of the child nodes' checkbox being checked.

The screenshot below shows a parent node whose checkbox is checked, and another whose checkbox is unchecked. Both nodes have one child node whose checkbox is checked.

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/14315611/84070350-dacd0a00-a980-11ea-8705-9d4ef425c830.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Accessibility Insights for Windows Version: 1.1.1248.1

**Comment by adarshrema** [comment] 2020-06-09 00:55
Confirmed with @guybark that the parent nodes for the event tree are,
* Expected events.. by control type
* My events

**Comment by DaveTryon** [comment] 2020-08-07 16:09
@guybark, this is fixed in https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1314.01. Please regress at your convenience

**Comment by DaveTryon** [comment] 2020-08-07 17:46
@guybark, I'd suggest regressing in https://github.com/microsoft/accessibility-insights-windows/releases/tag/v1.1.1314.02, just because that build has the fix that allows you to successfully switch channels

**Closed** 2020-08-14 20:00 UTC
Labels: bug, status: needs author feedback, status: no recent activity
