### ISSUE TITLE
[BUG] Color contrast algorithm returns NULL for certain images

### ISSUE THREAD

**Issue by babylonbee** [Microsoft/accessibility-insights-windows#231] opened 2019-03-28 16:55 UTC
**Describe the bug**
Color contrast algorithm returns NULL for certain images

**To Reproduce**
1. Pull the code from my [branch](https://github.com/babylonbee/accessibility-insights-windows/tree/color_contrast_test);
2. Navigate to the test cases: **_AccessibilityInsights.DesktopTests.ColorContrastAnalyzer.ImageTests.SimplePurpleAndWhiteButton_**
and
**_AccessibilityInsights.DesktopTests.ColorContrastAnalyzer.ImageTests.SimpleBlueAndWhiteText_**
3. Run or debug these test cases
4. See error as mostContrastingPair is **null**

**Expected behavior**
the _**mostContrastingPair**_ should return the most contrasting pair of the actual color of the image

**Actual behavior**
The **_mostContrastingPair_** value calculated from _**RunColorContrastCalculation**_ function is **null**.

**Screenshots or .GIF**

![simple_blue_and_white_text](https://user-images.githubusercontent.com/29690812/55176231-feba7c00-513d-11e9-8093-e7e63a58c0cd.jpg)
![simple_purple_and_white_button](https://user-images.githubusercontent.com/29690812/55176235-01b56c80-513e-11e9-925c-99555933e667.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1809] (Get the version by running `winver` from the command line)
 - Accessibility Insights for Windows Version:
 - Target Application: [e.g. Chrome, Wildlife Manager]
 - Target Application Version: [e.g. 22]

**Additional context**
Priority requested -

 The affected tests, _**SimplePurpleAndWhiteButton**_ and  **SimpleBlueAndWhiteText** should be uncommented after that issue is fixed

**Comment by neocln** [comment] 2019-03-29 17:21
@chriscm2006 do you have an ETA for this fix?

**Comment by chriscm2006** [comment] 2019-04-02 13:35
> @chriscm2006 do you have an ETA for this fix?

1. Not really. This is at least a little bit by design. The "Save" example doesn't have enough text. I'll detect a max of 5 similar contrast transitions in that image. This can be a lot of things, not necessarily text. I believe the min number of characters I would make a conclusion on is 10. One of my metrics is at least X transitions. So NULL here is expected. 
2. The number example is very blurry. The anti aliasing is blending things together and the gap isn't large enough. So within a given line we don't always return back to the same background color. To the algorithm it looks like this is a blended background. We MIGHT be able to come to a conclusion, but drawing a NULL conclusion from this, without logic changes, is a feature. As in, we're not coming to conclusions about things we can't be sure about.

For scenario 2 this might be something we can handle, but it's not a bug. This is actually a feature request. Handling scenario 2 better would require a change in logic OR a change in heuristics such that other scenarios may be handled worse. Lower confidence values for example.

**Comment by neocln** [comment] 2019-04-03 18:32
@chriscm2006 it sounds like that this would not be in the scope. if so, could you close this bug?

**Comment by neocln** [comment] 2019-04-09 00:33
close this issue since we don't have any plan to fix this by changing color contrast detection logic.

**Closed by neocln** 2019-04-09 00:33 UTC
Labels: bug
