### ISSUE TITLE
[BUG] AIWin unexpectedly reports a failure relating to a ComboBox's list having a name and localized control type that's the same as a sibling

### ISSUE THREAD

**Issue by guybark** [microsoft/accessibility-insights-windows#1041] opened 2021-02-05 20:01 UTC
AIWin unexpectedly reports a failure relating to a ComboBox's list having a name and localized control type that's the same as a sibling.

1. Install AI For Windows v1.1.1495.1.
2. In Visual Studio, created a WinForms app targeting .NET 6. (I used .NET 6.0 preview 1.21104.4)
3. Add a ComboBox to the app, and don't add any items to the ComboBox.
4. Give the ComboBox an accessible name. (I used the test name of "CB1".)
5. Run the app, expand the ComboBox's dropdown, and have AIWin do its fastpass on the dropdown list.

Result: AIWin reports a failure about the list having the same name and localized control type as a sibling.
Expected: AIWin doesn't report that because the list has no such sibling.

The first image below shows the UIA hierarchy beneath the ComboBox. There are two elements named "CB1", and one has a localized control type of "list", and the other has "edit". The second image below shows the failure being reported by AIWin.
 
![image](https://user-images.githubusercontent.com/14315611/107082920-b80e2200-67a9-11eb-8939-d895d8c7eca4.png)

![image](https://user-images.githubusercontent.com/14315611/107082944-c1978a00-67a9-11eb-97d5-aa07ed8a1860.png)

**Comment by pownkel** [comment] 2021-02-06 00:03
Hi @guybark, I'm having some trouble reproducing this issue. With .NET 5.0, I'm seeing no issues reported in automated checks. Do you only see this behavior with apps targeting .NET 6.0? If so, how can we get access to the preview versions of .NET?

**Comment by vladimir-krestov** [comment] 2021-02-07 21:55
Hi @pownkel, to test the preview of .NET 6.0, please download it from https://github.com/dotnet/installer 
![image](https://user-images.githubusercontent.com/49272759/107160416-181de780-69a7-11eb-90fc-abd32cf521e0.png)

.NET 5.0 has an incorrect ComboBox drop-down list position in an accessibility tree. Please compare the issue behavior .NET 6.0 and .NET Framework (any version)

Here are few points of my investigation about this issue: https://github.com/dotnet/winforms/issues/4408#issuecomment-770596693

Also, the 4th step of the reproduction in the description should be: 
> 4. "Give the **ComboBox** an accessible name. (I used the test name of "CB1".)"

**Comment by guybark** [comment] 2021-02-07 23:29
@vladimir-krestov, thanks for the details. I corrected my Step 4.

**Comment by RussKie** [comment] 2021-02-08 07:06
A bit of OT, it is generally a good idea to provide a small working sample, either attached to an issue or as a link to a GitHub repo 😉

**Comment by vladimir-krestov** [comment] 2021-02-08 07:26
Here is a .NET 6.0 test app:
[[AI-1041]ComboBox.zip](https://github.com/microsoft/accessibility-insights-windows/files/5941874/AI-1041.ComboBox.zip)

I just created the app, added a ComboBox on the form, and set "CB1" as a custom AccessbileName for the ComboBox

**Comment by RobGallo** [comment] 2021-02-08 16:42
@guybark  Using the app provided by @vladimir-krestov  I am unable to repro the issue. I expand the combo box, I press F8 to scan the app, and I get no errors. I have installed the latest .Net6 (master) from the GitHub page provided above. And I am running AIWin canary 1.1.1499.1.

Any thoughts?

**Comment by vladimir-krestov** [comment] 2021-02-08 18:07
![image](https://user-images.githubusercontent.com/49272759/107262353-7f907180-6a51-11eb-8488-280383a1f8ea.png)


![yOFzLsGQlu](https://user-images.githubusercontent.com/49272759/107262310-70a9bf00-6a51-11eb-87aa-a8c69a9a7ec1.gif)

**Comment by RobGallo** [comment] 2021-02-09 00:17
We are now able to reliably reproduce the issue.

In brief, the problem is that once one presses F8 to begin the scan, AIWin sets focus to its own window, which causes the combo box to collapse and the list box to disappear. At that point, AIWin is scanning an element that no longer exists.

To complicate matters, AIWin is actually still scanning the list box, but it has refreshed its internal model with the latest UIA data. So here's why we see this particular error about sibblings:

1. A user presses F8 to scan the list box
2. AIWin sets focus back to its own window causing the combo box to close and the list box to disappear
3. Before running the scan, AIWin grabs the latest UIA data which no longer contains the list box
4. However, AIWin still attempts to scan the list box element (its pointer to the element) which no longer exists in the UIA hierarchy of the app
4. In the SiblingUniqueAndFocusable rule, the rule asks for all the children of the parent of the list box (i.e., the combo box)
5. The code then tries to ensure that the parent at least contains one element matching the name and localized control type of the list box.
6. Because the current parent element contains no matching child element (i.e., the list box), the rule evaluation returns a rule exception error
7. Even though the rule returned an execution error rather than a failure, AIWin shows it as if it were a regular rule violation.
So, @guybark , you are correct there is no accessibility violation here, AIWin just shows it as if it were.

There are multiple layers of problem here to unpack:

1. AIWin is causing the element the user is trying to scan to disappear.
2. AIWin is trying to scan an element which no longer exists.
3. AIWin is reporting an error in rule execution as an accessibility error.

**Comment by guybark** [comment] 2021-02-10 16:55
@RobGallo - Hey Rob, thanks for all this in-depth investigation and helpful summary of what's going on. Perhaps at least things could change such that if this exception occurs, it doesn't get bubbled up as failure in the UI. I get how sometimes an exception may need to get bubbled up as a failure, given that some exceptions may be due to unexpected UIA provider behavior, and that might impact customers. 

On a side note, if I use AIWin's timer feature, to set the countdown on when the fast-pass starts, I can successfully run the test on the ComboBox with the dropdown list open without the list being closed.

**Comment by vladimir-krestov** [comment] 2021-02-10 18:13
Steps of the testing with the timer (just hover the dropped list by mouse without a click when the timer is working):

![Ibqm2Bbw7q](https://user-images.githubusercontent.com/49272759/107552481-a16e2d80-6be4-11eb-81d4-e6c8ec67ed53.gif)

**Comment by RobGallo** [comment] 2021-02-10 22:00
@guybark , I'm glad the timer approach works. I'm pretty sure this was the exact situation the timer was put in to address. We are going to kick around some ideas to see if we can't either ameliorate the problem, or at least make what's happening more obvious to users.

**Comment by ferBonnin** [comment] 2021-04-22 17:43
Removing for the board since its marked as needs investigation. @juchampa please add to the Accessibility Insights dashboard if there is dev action to take.

**Comment by DaveTryon** [comment] 2021-05-21 16:59
@juchampa, what do we want to do here? Using the timer works as expected, so it's a bit unclear what investment we want to make.

**Comment by RobGallo** [comment] 2021-11-10 15:25
My suggestion is we surface execution errors (e.g., exceptions) with a new icon (separate from the icon meant to indicate that web content is being scanned) and store exception information in the a11ytest file. This will enable users to quickly determine whether their issues are accessibility or execution/platform. It will also enable us to better diagnose issues when they are sent to us.

**Comment by RobGallo** [comment] 2021-11-10 15:35
Closing this issue because the original issue has a work around and because details for surfacing execution errors and distinguishing them from accessibility errors are being discussed in #1113

**Closed by RobGallo** 2021-11-10 15:35 UTC
Labels: bug, status: needs investigation
