### ISSUE TITLE
Accessibility Insights for Windows: Selection by mouse hover is difficult to use for nested and overlapped elements

### ISSUE THREAD

**Issue by petewu100** [microsoft/accessibility-insights-windows#1137] opened 2021-05-28 19:47 UTC
When using the "Inspect" tool in Accessibility Insights for Windows, it is difficult to select the element you want using "Selection by mouse hover" when there are nested or overlapped elements.

1. Load the following page in Edge: http://petewu-dev/overlap.1.htm.
2. Boot Accessibility Insights for Windows and use the Inspect tool with "Selection by mouse hover" on (which is the default setting).
3. Move the mouse over the white area of the page in the bottom-left.

=> Note: Accessibility Insights selects the document element as expected.

4. Move the mouse into the red part.

=> Note: Accessibility Insights still has the document element selected.

Expected: the group "red" element to be selected.

5. Move the mouse into the green part.

=> Note: now Accessibility Insights selected the group "red" element.

Expected: the group "green" element to be selected.

6. Move the mouse into the blue part.

=> Note: now Accessibility Insights selected the group "green" element.

Expected: the group "blue" element to be selected.

7. Move the mouse into the purple part.

=> Note: Accessibility Insights selects the document element.

Expected: the group "purple" element to be selected.

8. Wiggle the mouse.

=> Note: now Accessibility Insights selects the group "purple" element as expected.

9. Move the mouse into the yellow part (that is overlapping the purple part).

=> Note: Accessibility Insights still has the group "purple" element selected.

Expected: the group "yellow" element to be selected.

10. Move the mouse into the orange part (that is overlapping the purple and yellow parts).

=> Note: Accessibility Insights selects the group "yellow" element.

Expected: the group "orange" element to be selected.

It seems like Accessibility Insights is able to detect which is the innermost element and which is the top-most element, but it lags by one step in selecting that element. I think it would be much easier to use if it selected the innermost and top-most element right when you enter the element.  In the tree view it is easy to walk up to a parent element if you need to, but you can't get to child elements because the tree view doesn't show them until you have selected an element at that level.

See video recording on \\ppt-svc\user\petewu\AccessibilityInsights.SelectionByMouseHover.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 version 21H1 Build 19043.985
 - Accessibility Insights for Windows Version: 1.1.1562.2
 - Target Application: Edge
 - Target Application Version: 91.0.864.37

**Comment by DaveTryon** [comment] 2021-06-08 21:05
I added some logging to try to understand what's happening here, and AIWin is reflecting exactly what UIA is reporting. When moving "outward" through the concentric shapes, UIA reports a new RuntimeId as we move from blue to green to red. When moving "inward" through the shapes, UIA does not immediately report the new RuntimeId while moving from red to green to blue, which is the source of the lagging behavior that you're seeing. The RuntimeID properties similarly lag for the partially overlapping squares. There _is_ a problem here, but it's occurring upstream of AIWin.

Testing the same page in Chrome, UIA doesn't report any of the squares in live mode, so this problem seems to be unique to the interaction between Edge and UIA.

@petewu100,  the next logical step is probably to approach the Edge team to try to understand the root cause of the lag in the RuntimeID property that is being reported through UIA.

**Comment by petewu100** [comment] 2021-06-14 23:12
Thank you, @DaveTryon. Please log a bug against Edge at https://microsoft.visualstudio.com/edge. I don't think you need anything from me to be able to do that.

**Comment by DaveTryon** [comment] 2021-06-15 22:18
@petewu100, I've opened https://microsoft.visualstudio.com/Edge/_workitems/edit/33776905. Closing this out.

**Closed by DaveTryon** 2021-06-15 22:18 UTC
Labels: bug, status: needs attention, status: no recent activity
