### ISSUE TITLE
Spelling in docs/NewProject.md

### ISSUE THREAD

**Issue by AhmedAbdoOrtiga** [Microsoft/accessibility-insights-windows#203] opened 2019-03-21 00:45 UTC
**Describe the bug**

**To Reproduce**
Read [point 5](https://github.com/Microsoft/accessibility-insights-windows/blob/master/docs/NewProject.md#for-non-test-projects-only).

**Issue**
"Products.wxs" should be "Product.wxs", remove the 's' at the end.

**Screenshots or .GIF**
![image](https://user-images.githubusercontent.com/45858632/54727887-982ed000-4b37-11e9-9dd9-65cbfe89aa34.png)

![image](https://user-images.githubusercontent.com/45858632/54727904-b7c5f880-4b37-11e9-953b-0157c8a463bc.png)

**Comment by risanaka** [comment] 2019-03-21 17:57
Hi @AhmedAbdoOrtiga, this issues should be a duplicate of #204. If you agree, please close this issue.

**Comment by karanbirsingh** [comment] 2019-03-21 18:26
@risanaka #204 is the PR (not an issue) to fix this issue, just a heads up

**Comment by neocln** [comment] 2019-03-21 22:56
Removing duplicate tag based on Karan's comment. also fixed is validate. so it is closed.

**Closed by neocln** 2019-03-21 22:56 UTC
Labels: duplicate, needs author feedback

**Comment by risanaka** [comment] 2019-03-21 23:39
🤦‍♀️ my bad
