### ISSUE TITLE
[General Question] [NumericUpDown] The Name must not include the same test as the control type and LocalizedControlType

### ISSUE THREAD

**Issue by v-lga-hub** [microsoft/accessibility-insights-windows#618] opened 2019-10-24 07:16 UTC
**We encourage tool related questions to be asked on stackoverflow.com and tagged with `accessibility-insights`.**

**Your question here**
Make sure to provide enough context. If you have spoken to a team member please mention them here.
spinner just a part of NumericUpDown control in System.Windows.Forms. the name of spinner should not be changed by code. So **does this kinds of issue shouldn't be a accessibility defect?**
Add any items (screenshots etc) that will help.
![image](https://user-images.githubusercontent.com/56630584/67552879-84d38b00-f73e-11e9-9fed-fcc873a62896.png)

6-453e6d80-f670-11e9-8893-70ea0817e465.png)
[TestResults 10-24-19.zip](https://github.com/microsoft/accessibility-insights-windows/files/3766151/TestResults.10-24-19.zip)

**Comment by DaveTryon** [comment] 2019-10-28 22:55
@v-lga-hub, what you're seeing here is the same issue that is reported at microsoft/axe-windows#150 and dotnet/winforms#1588 (last updated on October 8th 2019). It represents a shortcoming in the Windows Forms NumericUpDown control, and is not something that would typically be fixed in your code. We know that the WinForms teams knows about this issue, but we don't have any specific visibility to know when a fix will become available.

There are 2 main ways to respond to this reported issue (in increasing risk)
1. Leave your code as is for now, and wait for an updated version of Windows Forms (that contains a fix), then upgrade to the new version of Windows forms. You'll need to include this reported issue in your VPAT (if your product needs one) until the issue is actually fixed.
2. Consider using a framework other than Windows Forms (nuclear option).

Please let us know if you have any additional questions. Thanks!

**Comment by RussKie** [comment] 2019-10-31 00:36
@m-lipin didn't we fix the spinner issue?

**Closed** 2019-11-07 02:00 UTC
Labels: status: needs author feedback, status: no recent activity

**Comment by M-Lipin** [comment] 2019-11-14 14:32
> @M-Lipin didn't we fix the spinner issue?

I can reproduce it in .NET Core 3.1, filed the bug: https://github.com/dotnet/winforms/issues/2370
